version: "3"

services:
  app:
    image: node:alpine
    user: node
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    command: "npm start"

# mongodb:
#   image: tutum/mongodb
#   environment:
#     - MONGODB_USER=mrsudo
#     - MONGODB_PASS=mrsudo

# redis:
#   image: redis:alpine
#   ports:
#     - 6379:6379

