nginx:
  image: vnought/nginx-dev
  ports:
    - "8080:80"
    - "3000:3000"
  volumes:
    - ./src/config/nginx.conf:/etc/nginx/conf.d/vhost.conf

mongodb:
  image: tutum/mongodb
  ports:
    - "27017:27017"
    - "28017:28017"
  environment:
    - MONGODB_USER=test
    - MONGODB_PASS=test
